<?php

namespace ContainerB8dTax3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSpreadsheetCommandService extends App_KernelLocalDebugContainer
{
    /**
     * Gets the private 'App\Infrastructure\Console\Command\SpreadsheetCommand' shared autowired service.
     *
     * @return \App\Infrastructure\Console\Command\SpreadsheetCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Console/Command/SpreadsheetCommand.php';

        $container->privates['App\\Infrastructure\\Console\\Command\\SpreadsheetCommand'] = $instance = new \App\Infrastructure\Console\Command\SpreadsheetCommand();

        $instance->setName('app:user:greet');

        return $instance;
    }
}
