<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNYZCmSu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNYZCmSu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNYZCmSu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNYZCmSu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNYZCmSu\App_KernelDevDebugContainer([
    'container.build_hash' => 'NYZCmSu',
    'container.build_id' => '38b31865',
    'container.build_time' => 1745288545,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNYZCmSu');
