<?php

namespace ContainerNYZCmSu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProcessXmlToSheetsCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Adapters\Console\ProcessXmlToSheetsCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Adapters\\Console\\ProcessXmlToSheetsCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('sync:xml-to-sheets', [], 'Processes a local or remote XML file and syncs its data to a Google Sheet.', false, #[\Closure(name: 'App\\Adapters\\Console\\ProcessXmlToSheetsCommand')] fn (): \App\Adapters\Console\ProcessXmlToSheetsCommand => ($container->privates['App\\Adapters\\Console\\ProcessXmlToSheetsCommand'] ?? $container->load('getProcessXmlToSheetsCommandService')));
    }
}
