<?php

namespace ContainerNYZCmSu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProcessXmlToSheetsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Adapters\Console\ProcessXmlToSheetsCommand' shared autowired service.
     *
     * @return \App\Adapters\Console\ProcessXmlToSheetsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Adapters/Console/ProcessXmlToSheetsCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Application/File/Factory/FileFetcherFactory.php';
        include_once \dirname(__DIR__, 4).'/src/Application/Config/Contract/ExternalFeedSourceConfigContract.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Config/ExternalFeedSourceYamlConfig.php';
        include_once \dirname(__DIR__, 4).'/src/Application/Config/Contract/FileSourceConfigContract.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Config/FileSourceEnvConfig.php';
        include_once \dirname(__DIR__, 4).'/src/Application/Parser/Contract/XmlParserContract.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Parser/SimpleXmlParser.php';
        include_once \dirname(__DIR__, 4).'/src/Application/Product/Contract/ProductFactoryContract.php';
        include_once \dirname(__DIR__, 4).'/src/Application/Product/Factory/ProductSupCoffeeFeedFactory.php';
        include_once \dirname(__DIR__, 4).'/src/Application/GoogleDocument/contract/CreateContract.php';
        include_once \dirname(__DIR__, 4).'/src/Application/GoogleDocument/contract/WriteContract.php';
        include_once \dirname(__DIR__, 4).'/src/Application/GoogleDocument/contract/ProcessContract.php';
        include_once \dirname(__DIR__, 4).'/src/Application/GoogleDocument/Sheet/Contract/GoogleSpreadsheetContract.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/GoogleDocument/Sheet/GoogleSpreadSheet.php';
        include_once \dirname(__DIR__, 4).'/src/Application/Cache/Contract/CacheContract.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Cache/RedisCache.php';
        include_once \dirname(__DIR__, 4).'/vendor/predis/predis/src/ClientInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/predis/predis/src/Client.php';
        include_once \dirname(__DIR__, 4).'/src/Application/Config/Contract/GoogleSheetConfigContract.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Config/GoogleSheetEnvConfig.php';
        include_once \dirname(__DIR__, 4).'/src/Application/Logger/Contract/LoggerContract.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Logger/MonoLogger.php';
        include_once \dirname(__DIR__, 4).'/src/Application/File/Contract/FileSaverContract.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/File/Save/XmlFileSaver.php';

        $a = new \App\Infrastructure\Config\FileSourceEnvConfig();

        $container->privates['App\\Adapters\\Console\\ProcessXmlToSheetsCommand'] = $instance = new \App\Adapters\Console\ProcessXmlToSheetsCommand(new \App\Application\File\Factory\FileFetcherFactory(new \App\Infrastructure\Config\ExternalFeedSourceYamlConfig($a)), $a, new \App\Infrastructure\Parser\SimpleXmlParser(), new \App\Application\Product\Factory\ProductSupCoffeeFeedFactory(), new \App\Infrastructure\GoogleDocument\Sheet\GoogleSpreadSheet(new \App\Infrastructure\Cache\RedisCache(new \Predis\Client($container->getEnv('REDIS_URL'))), new \App\Infrastructure\Config\GoogleSheetEnvConfig(), $a), new \App\Infrastructure\Logger\MonoLogger(($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService'))), new \App\Infrastructure\File\Save\XmlFileSaver($a));

        $instance->setName('sync:xml-to-sheets');
        $instance->setDescription('Processes a local or remote XML file and syncs its data to a Google Sheet.');

        return $instance;
    }
}
