<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY6G4s3m\App_KernelLocalDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY6G4s3m/App_KernelLocalDebugContainer.php') {
    touch(__DIR__.'/ContainerY6G4s3m.legacy');

    return;
}

if (!\class_exists(App_KernelLocalDebugContainer::class, false)) {
    \class_alias(\ContainerY6G4s3m\App_KernelLocalDebugContainer::class, App_KernelLocalDebugContainer::class, false);
}

return new \ContainerY6G4s3m\App_KernelLocalDebugContainer([
    'container.build_hash' => 'Y6G4s3m',
    'container.build_id' => '8dd20816',
    'container.build_time' => 1745307151,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY6G4s3m');
