<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEOZSigK\App_KernelLocalDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEOZSigK/App_KernelLocalDebugContainer.php') {
    touch(__DIR__.'/ContainerEOZSigK.legacy');

    return;
}

if (!\class_exists(App_KernelLocalDebugContainer::class, false)) {
    \class_alias(\ContainerEOZSigK\App_KernelLocalDebugContainer::class, App_KernelLocalDebugContainer::class, false);
}

return new \ContainerEOZSigK\App_KernelLocalDebugContainer([
    'container.build_hash' => 'EOZSigK',
    'container.build_id' => 'c6ecc6cc',
    'container.build_time' => 1745362758,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEOZSigK');
