<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMG8t2sW\App_KernelLocalDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMG8t2sW/App_KernelLocalDebugContainer.php') {
    touch(__DIR__.'/ContainerMG8t2sW.legacy');

    return;
}

if (!\class_exists(App_KernelLocalDebugContainer::class, false)) {
    \class_alias(\ContainerMG8t2sW\App_KernelLocalDebugContainer::class, App_KernelLocalDebugContainer::class, false);
}

return new \ContainerMG8t2sW\App_KernelLocalDebugContainer([
    'container.build_hash' => 'MG8t2sW',
    'container.build_id' => '3e33d8bd',
    'container.build_time' => 1745374481,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMG8t2sW');
